permissions:
  contents: read
name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: JasonAllenCorns_waveform-atlas
          organization: ji8jolij-asase3
          projectName: waveform-atlas
          projectVersion: 1.0
          sources: .
          tests: .
          testInclusions: '**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx'
          lcovReportPaths: coverage/lcov.info
          sourceEncoding: UTF-8